### ISSUE TITLE
stop using multiprocessing

### ISSUE THREAD

**Issue by mmerickel** [Pylons/hupper#17]
Several interesting issues have arisen in my many hours fighting multiprocessing. The most obvious is the issue with forwarding stdin to the subprocess which requires terrible hacks, especially on windows.

However another much more subtle issue is this... on unix multiprocessing by default does not fork+exec. It only forks. This is interesting because it uses the original python interpreter. The issue is that any libraries that were already imported are not re-imported into the child process because they are already found in memory. Instead we would prefer to fork+exec a new subprocess which uses its own interpreter to get a fresh system. To be more clear, if you import a library prior to `hupper.start_reloader` and then you try to develop on that library, it will not be reloaded even though hupper says it restarted.

**Comment by miohtama** [comment]
We run the similar issue with [sauna.reload](https://pypi.python.org/pypi/sauna.reload/).

The goal was to optimize the reload time, so that Python interpreter and part of the libraries are preloaded for every spawned new child. The process was something along the lines:

* Parent starts Python interpreter
* Parent loads X core Python libraries, parses XML and such (in our case, I'd say it be stdlib and maybe Pyramid itself for an average developer) - these are not reloadable
* Fork point (explicitly)
* Child continues to the rest of the Python libraries, including the libraries you are developing
* Any library you want to develop must be imported so that it is loaded after the fork point

sauna.reload is very explicity about reloads and prints out the libraries it managed to reload.

**Comment by piotr-dobrogost** [comment]
Have you seen [Python multiprocessing is different under Linux and Windows](http://rhodesmill.org/brandon/2010/python-multiprocessing-linux-windows/)?

Brian Tom [comments](http://rhodesmill.org/brandon/2010/python-multiprocessing-linux-windows/#comment-2894827468):

> I'm not sure if it was always there, but mulitprocessing allows you to test windows compatibility by letting you call mp.set_start_method('spawn'). This is essentially the same as windows starting a process

**Comment by mmerickel** [comment]
I actually tried to use `set_start_method('spawn')` and ran into lots of issues on windows related to how I'm passing file descriptors (which has been endless amounts of pain already). The only acceptable solution I will consider at this point is to use subprocess. Multiprocessing has been a very serious time sink for me that I'm ready to move on from.

**Comment by piotr-dobrogost** [comment]
Have you filed bugs for issues you ran into when using multiprocessing? Is there a public list of them?

**Comment by digitalresistor** [comment]
@piotr-dobrogost I have a feeling that a lot of them are simply due to the design and requirements of hupper that are not very useful in the more general sense where multiprocessing is generally used.

**Comment by jvanasco** [comment]
FYI, this new hupper version seems to have fixed the issues I had in 1.7.x -> 1.8.x migration on osx.

https://groups.google.com/forum/#!topic/pylons-discuss/6g-scld8Rik
