### ISSUE TITLE
watchman runs out of inotify instances because '/usr/lib/python2.7' is being watched

### ISSUE THREAD

**Issue by jjmurre** [Pylons/hupper#34]
When using pserve the number of inotify instances explodes. Lots of these errors:

 ```
The user limit on the total number of inotify instances has been reached; increase the 
  fs.inotify.max_user_instances sysctl

```
I am running watchman. It turns out that the watchlist gets huge, and contains the path '/usr/lib/python2.7', which means that effectively all python libs are being watched. 

I am running inside a virtualenv. Is there maybe something wrong in my configuration? 

For now, I downgraded to hupper 1.2 to solve the problem.

**Comment by mmerickel** [comment]
Thanks for the report. What OS are you using? I assume that increasing `fs.inotify.max_user_instances` will solve the problem, correct?

Watchman monitors directories, as such I don't see a scenario where it wouldn't monitor `/usr/lib/pythonX.Y` for any changes unless we feel it should only monitor user code which would be a change of scope for hupper.

Instead of downgrading you can just select a different file monitor via env variable, for example `HUPPER_FILE_MONITOR=hupper.polling.PollingFileMonitor`.

**Comment by jjmurre** [comment]
I increased max_user_instances to 1524288, that still was not enough.
Tx. for the info abou HUPPER_FILE_MONITOR. Is it also possible to set a certain root path, that limits the range of where watchman is looking?

**Comment by mmerickel** [comment]
version 1.4 will not monitor installed packages, hopefully this helps!

**Comment by merwok** [comment]
FTR PR was https://github.com/Pylons/hupper/pull/40
