### ISSUE TITLE
Chameleon-cache triggers reload

### ISSUE THREAD

**Issue by sallner** [Pylons/hupper#43]
I have a Zope based application and want to run waitress instead of paster as wsgi server, but keep the reload feature for development. Unfortunately, when running
`./bin/hupper -m my.entry.point ./paste.ini`
A reload is triggered when a file in the chameleon-cache `./var/chameleon-cache` changes. Is there a possibility to exclude this directory from the monitored files?

This issue occurred on current (Arch-)Linux and MacOS with 
hupper 1.4
Zope 4.0b7
Chameleon 3.5
and there respective dependencies.

Thanks for this nice tool!

**Comment by mmerickel** [comment]
Right now hupper does not have any way to ignore specific folders and I can't imagine there is anything about the chameleon-cache folder that I could detect to do it automatically that wouldn't negatively impact some other type of auto-generated folder. At least at this point I'm not interested in adding an ini file or anything but I'd accept a PR that added some `ignore_paths` argument to `start_reloader` that would be list of path prefixes to ignore. You could then write your own little script that invoked `start_reloader` however you wished.

```python
if __name__ == '__main__':
    start_reloader('my.entry.point', ignore_paths=[...], worker_args=['./paste.ini'])
```

The main issue is that it cannot easily be done at runtime because every file watcher impl would need to be updated to support removing paths. Currently they only support watching more paths as the app runs. The ignore prefixes would need to be static and defined when the reloader begins so those paths never make it to the file watchers.

**Comment by sallner** [comment]
Thanks for the quick reply. I was pondering on my own on the way the files are collected, but it was rather difficult. I will see, whether this issue has a high enough priority to invest some time and work on a PR.

Static prefixes should, in principle, be sufficient for this issue.

**Comment by sallner** [comment]
We have found a different solution, so I close this issue.

**Comment by digitalresistor** [comment]
@sallner Hupper now has support for ignoring files too!

**Comment by sallner** [comment]
Cool, good to know for the next time. :+1:
