### ISSUE TITLE
Worker termination by reloader may hang forever

### ISSUE THREAD

**Issue by marc1n** [Pylons/hupper#47]
Some worker processes could ignore SIGTERM signals. In such cases terminating reloader process ends with reloader process waiting for worker termination forever (in `self.worker.join()`).

Ugly result is that killing reloader in this state makes worker process orphan.

It seems reasonable that reloader should wait for worker termination with some (short) timeout and then kill worker with SIGKILL.

**Comment by marc1n** [comment]
Current Worker class code fragment (https://github.com/Pylons/hupper/blob/master/src/hupper/worker.py#L173):
```python
    def terminate(self):
        self.terminated = True
        self.process.terminate()

    def join(self):
        self.exitcode = self.process.wait()
        # ...
```

My change proposal is:
```python
    def terminate(self):
        self.terminated = True
        self.process.terminate()

    def join(self):
        if self.terminated and self.process.poll() is None: # Terminated but still alive
            time.sleep(1)
            if self.process.poll() is None:
                print('Signal SIGTERM was ignored, sending SIGKILL!')
                self.process.kill()
        self.exitcode = self.process.wait()
        # ...
```

What do you think?

**Comment by mmerickel** [comment]
I'd be fine with making the kill more aggressive. The current algorithm is to expect the SIGINT to propagate through the process group, and then if it's still running after 1 second, to issue a SIGTERM. My suggestion would be to just make `worker.terminate()` do a `process.kill()` which is a SIGKILL on non-windows systems. I'm not sure that your proposed 3 step fallback is better than this.

**Comment by mmerickel** [comment]
Also, not to state the obvious or anything but if a process is intercepting a SIGTERM and not dying eventually then it's doing it wrong.

I should note that right now in a reload scenario (my previous comment only addresses the SIGINT scenario to the reloader process) hupper just issues the SIGTERM and then waits for it to die. A fallback here sounds reasonable to a SIGKILL. So I think ideally we have two shutdown paths that are just two-steps each. SIGINT -> SIGKILL or SIGTERM -> SIGKILL. Do you see a path to making that happen or disagree that's better? Your proposed fix in `.join` would make it SIGINT -> SIGTERM -> SIGKILL, and SIGTERM -> SIGKILL.

**Comment by marc1n** [comment]
Yes, I agree that path SIGINT -> SIGKILL is better that SIGINT -> SIGTERM -> SIGKILL.
How can we achieve this?

Maybe we could add `Worker.kill` method and use it in `except KeyboardInterrupt` clause in `Reloader._run_worker`?

**Comment by mmerickel** [comment]
Well the hupper currently does SIGINT->SIGTERM when you ctrl-c the program and if you change a file to trigger a reload it just does a SIGTERM. That logic is fully contained here: https://github.com/Pylons/hupper/blob/91f57b28a1bde067e8c14ffea1e5b45c6911a902/src/hupper/reloader.py#L179-L198

I tried to pseudocode this out in the context of the current flow and the details are actually fairly tricky because of all scenarios hupper is trying to deal with. For example, hupper is trying to track whether the process crashed or not, and so when hupper kills the process we don't want it to look like a crash. I **think** the final solution will be to implement a worker.kill method that we use instead of terminate, and between the while loop and the finally there should be a spot there that does a SIGTERM+sleep but I don't have time as I'm writing this to get into the details enough to be sure. If this doesn't make sense I'll have to find more time to get into the weeds here.
