### ISSUE TITLE
Hupper does not seem to forward SIGTERM/SIGINT to the subprocess 

### ISSUE THREAD

**Issue by shughes-uk** [Pylons/hupper#64]
Hupper seems to avoid forwarding SIGTERM/SIGINT to the child process. It would be quite nice if it forward them. Especially SIGTERM as hupper does not seem to anything at all in response to that signal. 

This need comes from developing my applications responses to said signals. As the default behavior for hupper on SIGINT seems to be to exit, an optional flag to simply forward it would be pretty handy.

**Comment by mmerickel** [comment]
How are you sending a sigint right now? If you ctrl-c in the shell then bash will send the sigint to every process in the group by default, and hupper does not prevent that. If you use the `kill` command or other approaches then the signal will only go to the process PID you specify.

Basically hupper doesn't do anything to prevent signals going to subprocesses - it follows standard process tree behaviors. As you noticed it doesn't do anything at all with SIGTERM.

I think what hupper does right now is correct and it's not normal for a process to catch a signal just to send it to a subprocess. I'm open to some examples but for now I don't consider this a feature I'd add to hupper.

**Comment by shughes-uk** [comment]
Hupper is running inside a docker container. It’s when I try to stop the docker container gracefully this becomes an issue. I’m honestly not sure the exact mechanism docker uses to send sigterm but the docker documentation does mention it sends it to PID 1 and only that PID rather than the bash ctlc behavior.

I’m kind of stuck as either the hupper behavior is changed , I manage to convince the docker devs to make a change to their kill behavior , or I use something besides hupper. As it stands I  can’t use hupper and test functionality around graceful shutdowns of my application. At least without avoiding docker, which is an important part of our development flow

**Comment by mmerickel** [comment]
Ok, so it took me a while to remember what's going on.

Right now hupper will do a graceful shutdown when it receives a SIGINT. However, it's only graceful in the ctrl-c scenario where bash sends the SIGINT to both processes. Otherwise it will wait a few seconds then terminate the subprocess itself and shutdown.

It doesn't handle SIGTERM at all right now, so hupper will just die, and then the subprocess will see its parent is dead and terminate itself.

It seems to me the feature request is for hupper to support a graceful shutdown via either SIGINT or SIGTERM - which right now it only does correctly via ctrl-c.

I don't know how to handle this properly but I can say that it's done the way it is right now due to the ctrl-c issue. If hupper forwarded a SIGINT in that scenario, the subprocess would receive a double SIGINT and that's not correct. I'd need some guidance on how to improve this situation.

@bertjwregeer any thoughts on how hupper could handle this better?

I'm halfway tempted to get rid of the graceful shutdown in hupper when receiving a SIGINT. Then it won't be graceful ever but at least it'd be consistent. As hupper is not intended to be used for non-development work, it's not really intending to support a graceful shutdown. The only real goal is to support a graceful reload. I added in the nice shutdown on ctrl-c as a convenience because it was easy, but I can see how it breaks these other scenarios.

**Comment by shughes-uk** [comment]
So my argument in this is that when developing an app you often need to make sure you support a graceful shutdown (in my case our app has to wait for certain tasks to finish before exiting).  Removing graceful shutdown would mean I'd have to edit our dev run scripts to remove hupper each time I needed to work on that feature.

**Comment by mmerickel** [comment]
I think the fix I would apply is this:

1) Add SIGTERM support to hupper to catch the signal and trigger the current graceful shutdown logic that hupper users to send a SIGTERM to the subprocess and wait for it to die. I think this is probably uncontroversial.

2) Change how hupper handles a SIGINT so that it works in some cases but doesn't fail like it does right now. I'd basically tweak it to catch the SIGINT and send a SIGTERM to the subprocess. I'd also modify the subprocess to squash SIGINT by default. The scenarios this would create:

- Via Ctrl-C the subprocess may receive a SIGTERM and a SIGINT. The SIGINT would be squashed, and the SIGTERM would trigger normal graceful shutdown or immediate exit.

- The subprocess may override the default SIGINT squashing to handle it directly - at which point it'll likely trigger something weird where it receives both a SIGTERM and a SIGINT but this case is more rare.

- Via manual SIGINT this would just send a SIGTERM to the subprocess which it could handle or not.

Thoughts?

**Comment by shughes-uk** [comment]
I think this would work pretty well for my use case. Especially combined --shutdown-interval flag (to give our app extra time to shut down).

**Comment by mmerickel** [comment]
@shughes-uk I released 1.10, let me know how it goes.

**Comment by shughes-uk** [comment]
Hiya, I've integrated and found it works pretty great, thanks for the changes! Developing our SIGTERM response is way less fussy now now.

**Comment by mmerickel** [comment]
great! glad to hear it
